### ISSUE TITLE
control flow support in deepvm

### ISSUE THREAD

**Issue by chinesebear** [deeplang-org/deepvm#22]
![image](https://user-images.githubusercontent.com/13201054/135013110-fd6e5fcd-2067-4dd2-b64a-93efff134d7a.png)

**Comment by chinesebear** [comment]
![image](https://user-images.githubusercontent.com/13201054/135097388-b416ba63-6adb-42ba-b415-812d5391ea59.png)

**Comment by chinesebear** [comment]
![image](https://user-images.githubusercontent.com/13201054/135099594-9aeadd8f-2144-4d1e-8791-30c4d4ddc543.png)

**Comment by chinesebear** [comment]
自己==字节

**Comment by chinesebear** [comment]
![2021-09-28-234137_1920x1080_scrot](https://user-images.githubusercontent.com/13201054/135120449-cc2e50ad-a923-4b7c-ac5b-dc078ba30415.png)
raspberry pi 3B: control flow well done!

**Comment by chinesebear** [comment]
![2021-10-09-214403_1920x1080_scrot](https://user-images.githubusercontent.com/13201054/136660366-be93fa0d-1742-4e1e-9090-e6a1588e34f9.png)
only one case to adapt.

**Comment by sorrowfulT-Rex** [comment]
> ![2021-10-09-214403_1920x1080_scrot](https://user-images.githubusercontent.com/13201054/136660366-be93fa0d-1742-4e1e-9090-e6a1588e34f9.png) only one case to adapt.

Yes, the switch case
